labs = int(input("Enter the number of labs completed: "))
quizzes = int(input("Enter the number of quizzes completed: "))
a1 = int(input("Enter grade for Assignment 1: "))
a2 = int(input("Enter grade for Assignment 2: "))
a3 = int(input("Enter grade for Assignment 3: "))
a4 = int(input("Enter grade for Assignment 4: "))
m1 = int(input("Emter grade for Midterm 1: "))
m2 = int(input("Enter grade for Midterm 2: "))
f = int(input("Enter grade for Final Exam: "))
prep = int(input("Enter grade for Midterms and Final Preparation: "))
gl = (labs/6 * 20)
gq = (quizzes/6 * 15)
ga = (a1/100 * 4 + a2/100 * 4 + a3/100 * 4 + a4/100 * 4)
gm = (m1/100 * 12.5 + m2/100 * 12.5)
gf = (f/100 * 18)
gp = (prep/100 * 6)
x = str(gl + gq + ga + gm + gf + gp)
print("Your grade is: " + x)
